name: Build

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.6
    - name: Dependencies
      run: bash ./dependencies.sh
      shell: bash
    - name: Build project
      uses: threeal/cmake-action@v1.3.0
