name: Build

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1.4.2
        with:
          packages: |
            build-essential \
            cmake \
            curl \
            git \
            libasio-dev \
            libeigen3-dev \
            libopencv-dev \
            libopenscenegraph-dev \
            libqglviewer-dev-qt5 \
            libtinyxml2-dev \
            python3-dev \
            python3-pybind11 \
            qtbase5-dev

      # - name: Restore dependencies cache
      #   uses: actions/cache@v4
      #   id: restore-dependencies
      #   with:
      #     path: /usr/local
      #     key: dependencies-${{ runner.os }}-${{ github.sha }}-${{ github.run_id }}
      #     restore-keys: |
      #       dependencies-${{ runner.os }}-${{ github.sha }}
      #       dependencies-${{ runner.os }}
      - name: Dependencies
        #if: steps.restore-dependencies.outputs.cache-hit != 'true'
        run: bash ./dependencies.sh
        shell: bash
      - name: Restore build cache
        uses: actions/cache@v4
        id: restore-build
        with:
          path: ${{ github.workspace }}/build
          key: build-${{ runner.os }}-${{ github.sha }}-${{ github.run_id }}
          restore-keys: |
            build-${{ runner.os }}-${{ github.sha }}
            build-${{ runner.os }}
      - name: Build project
        uses: threeal/cmake-action@v2.0.0
        with:
          build-dir: ${{ github.workspace }}/build
      - name: echo
        run: ls -la
